---
- hosts: pi
  # strategy: debug
  remote_user: pi
  become: yes
  roles:
    - apt
    - build
    - elixir
  tasks:
    - apt: name=mosh state=latest
    - apt: name=fish state=latest
    - apt: name=tmux state=latest
