---
- hosts: pi
  # strategy: debug
  remote_user: pi
  become: yes
  roles:
    - fix
    - apt
    - build
    - elixir
    - app
    - tools
    - role: jdauphant.nginx
      nginx_sites:
        default:
          - listen 80
          - location / {
            proxy_pass http://web;
            proxy_set_header Host $host;
            }
      nginx_configs:
        upstream:
          - upstream web { server 127.0.0.1:5000; }
