---
- hosts: pi
  remote_user: pi
  become: true
  tasks:
  - name: Copy Elixir install script
    copy: src=install-elixir.sh dest=/home/pi/install-elixir.sh owner=pi group=pi mode=600
  # - name: Install Elixir
  #   command: sh install-elixir.sh
