---
- hosts: pi
  remote_user: pi
  become: true
  tasks:
  - name: Copy Erlang install script
    copy: src=install-erlang.sh dest=/home/pi/install-erlang.sh owner=pi group=pi mode=600
  # - name: Install Erlang
  #   command: sh install-erlang.sh
