---
- name: Install a lot of packages
  apt:
    name:
      - git
      - build-essential
      - ncurses-dev
      - libncurses5-dev
      - gettext
      - autoconf
    state: latest
    update_cache: true
