#!/bin/sh

echo BUILDING
./scripts/build
# (cd _build/armv7/prod/rel || exit; tar tvzf - hello) | ssh pi@hem.karleklund.se tar xvzf -
echo COPYING
rsync -r _build/armv7/prod/rel/hello/* pi@hem.karleklund.se:hello
echo RESTARTING
ssh hem.karleklund.se "sudo systemctl restart hello"
