#!/bin/sh

ssh hem.karleklund.se "git clone https://github.com/kek/sofa; cd sofa; git status; git checkout -- .; git pull; ./scripts/build; sudo rsync -r _build/prod/rel/hello/* ~pi/hello; sudo chown -R pi:pi ~pi/hello; sudo systemctl restart hello"
