---
- hosts: pi
  # strategy: debug
  remote_user: pi
  become: true
  roles:
    - fix-wlan
    - apt
    - build-deps
    - app
    - tools
    - service-files
    - role: jdauphant.nginx
      nginx_sites:
        default:
          - listen 80
          - location / {
            proxy_pass http://web;
            proxy_set_header Host $host;
            }
      nginx_configs:
        upstream:
          - upstream web { server 127.0.0.1:5000; }
